# Generated by Django 5.0.7 on 2024-08-19 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ABDULLAHI USMAN', max_length=100)),
                ('occupation', models.CharField(default='Backend Engineer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=25)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentdetails.parent')),
            ],
        ),
    ]
