# Generated by Django 5.0.7 on 2024-08-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='parent_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
