# Generated by Django 5.0.7 on 2024-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0002_rename_phone_student_parent_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
