# Generated by Django 5.0.7 on 2024-08-19 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0003_remove_student_dob_student_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentdetails.parent'),
        ),
    ]
